name: ecom
description: "ecommerce store"
version: 1.0.1+3

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  http: ^1.2.1
  cached_network_image: ^3.3.1
  logging: ^1.2.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/local/
   - assets/fonts/

  fonts:
    - family: NotoSansThai
      fonts:
        - asset: assets/fonts/NotoSansThai-Regular.ttf
    
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf